### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by slightlytyler** [binygal/jest-runner-flowtype#2]
`jest: ^22.4.0`
`flow-bin: ^0.52.0`
You can check the CLI behavior here http://recordit.co/04raBV1z8B. Any ideas? Would love to get flow into our jest setup

**Comment by binygal** [comment]
Is the problem the blinking part or the checks just don't ever finish?

**Comment by slightlytyler** [comment]
It doesn't look like it finishes lol. Guessing you don't experience this behavior?

**Comment by binygal** [comment]
No. But let's figure it out. Some of the checks are passing. right?

**Comment by slightlytyler** [comment]
Some are passing, if I run it with `CI=true` it completes and I see a tremendous amount of issues related to import statements. Not seeing these issues when using flow independently...

**Comment by slightlytyler** [comment]
Looks related to #1

**Comment by slightlytyler** [comment]
Also related https://github.com/facebook/flow/issues/1451

**Comment by binygal** [comment]
I will take another look. I think I have a clue what's going on.

**Comment by slightlytyler** [comment]
Seems that `flow check-contents` doesn't work. I did research on a runner like this initially and it appeared that you had to use `flow` (which checks everything) once at runner start and then map the results to the individual test success / failure. I'd love to see this working in some fashion though

**Comment by binygal** [comment]
Running Flow on the whole project and mapping the results seems like a violation of the jest runners concept.
I'm considering using flow focus-check. 
I have 2 issues with it, it's not documented yet and I think it will show errors on depended files. (for example if b is dependent on a and a have issues, b will also show a issues).
I will try it later today.

**Comment by binygal** [comment]
This is the documentation from the CLI to `flow focus-check` 

> focus-check     EXPERIMENTAL: Does a focused Flow check on a file (and its dependents and their dependencies) and prints the results

And I find some performance issues with it so I will drop that direction. I will implement this [suggestion](https://github.com/binygal/jest-runner-flowtype/issues/2#issuecomment-367578393)
@slightlytyler Do you have any suggestion to handle watch mode and reruns?

**Comment by slightlytyler** [comment]
I think `focus-check` looks like the answer. They (flow team) have talked about moving to a model where it follows dependencies rather than scanning directories and I'm guessing that's it. I'm not sure if my suggestion is truly feasible but it did come from a conversation with @rogeliog. If you decide to go that route I think we can come up with some way to hack it together

**Comment by binygal** [comment]
`focus-check` is checking the files that depend on the checked file. (If a imports b, focus-check on a will check b as well and it's not efficient at all, it took 6 sec. for checking 5 files in my test project today).
I looked at creat-jest-runner today and it seems that adding the ability to pass data to the jest-workers is something that we will need to implement in our own (if we want to run flow once and pass the data to the workers for each file under test).
I think that having @rogeliog thoughts on it is a great suggestion.

**Comment by rogeliog** [comment]
I don't have a strong opinion for either, although I agree we need to go for an efficient solution.

>I looked at creat-jest-runner today and it seems that adding the ability to pass data to the jest-workers is something that we will need to implement in our own
It would be awesome if we add some of that to create-jest-runner. It sounds great to have to have it at that level so that other runners can benefit from it. I'm not sure how the interface for that would look though.

**Comment by binygal** [comment]
I've opened an issue in Create-Jest-Runner to discuss the interface [#3](https://github.com/rogeliog/create-jest-runner/issues/3). I started with suggesting the naive approach.

**Comment by binygal** [comment]
@slightlytyler I almost finish with the code. Will it be ok to ask you to review it when I'm done?

**Comment by binygal** [comment]
I would love to have comments on my PR. https://github.com/binygal/jest-runner-flowtype/pull/3

**Comment by binygal** [comment]
I fixed it and published to npm. Please reopen if you find those issues in the new version.
