### ISSUE TITLE
Usage in multi-project runner broken

### ISSUE THREAD

**Issue by sgwilym** [binygal/jest-runner-flowtype#5]
I'm trying to use this runner as part of a multi-project runner in a monorepo with multiple workspaces, which runs against a few of the assumptions the implementation here makes:

- That `flow` is available from the current working directory (https://github.com/binygal/jest-runner-flowtype/blob/initial/src/FlowtypeRunner.js#L13)
- That the files being tested against are in the current working directory (https://github.com/binygal/jest-runner-flowtype/blob/initial/src/FlowtypeRunner.js#L19)

I was able to fix this by switching out `process.cwd()` for `this.globalConfig.rootDir`.

Is this a viable approach (in which case I'll open a PR), or are there some drawbacks to this that I'm not seeing and we should find another way?

**Comment by binygal** [comment]
I think it's ok, just make sure it passes the tests. I didn't set CI/CD for this repo yet so you need to run them manually. 

Also, your change is not fixing the first issue you mentioned, right? If not, please add this point to the README file in your PR.

**Comment by sgwilym** [comment]
This change would address the first issue too, as I'd expect the package that uses flow typechecking to have `flow-bin` as a dependency.
