### ISSUE TITLE
Runner ignores errors in test files

### ISSUE THREAD

**Issue by slightlytyler** [binygal/jest-runner-flowtype#8]
When checked via the runner I get no errors but when running `flow` directly I get the correct errors

**Comment by slightlytyler** [comment]
Looks like `fileNameMatcher` is invalid given a `firstErrorLine` like 
`: src/features/image/components/ImageList/ImageList.test.js:152`

**Comment by binygal** [comment]
@slightlytyler version 0.0.6 fixes this issue.
